// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    xcoffee
    (
        init => init
        donate => donate
        create_user_subscription => create_user_subscription
        renew_subscription => renew_subscription
        cancel_subscription => cancel_subscription
        getUserSubscriptionDeadline => get_user_subscription_deadline
        subscriptions_count => subscriptions_count
        subscriptions => subscriptions
        user_subscriptions => user_subscriptions
        subscription_user => subscription_user
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
